eureka:
  instance:
    prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: false
      service-url:
        defaultZone: ${$EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
 
 okta:
  oauth2:
    issuer: https://dev-84210673.okta.com/oauth2/default
    audience: api://default
